apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.local
      http:
        paths:
          - path: /myfirstapp
            pathType: Prefix
            backend:
              service:
                name: myfirstapp-service
                port:
                  number: 80
          - path: /mysecondapp
            pathType: Prefix
            backend:
              service:
                name: mysecondapp-service
                port:
                  number: 80
          - path: /mythirdapp
            pathType: Prefix
            backend:
              service:
                name: mythirdapp-service
                port:
                  number: 80
