apiVersion: v1
kind: Service
metadata:
  name: myfirstapp-service
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: myfirstapp
  ports:
    - port: 80          # Service port
      targetPort: 80   # Container port

---

apiVersion: v1
kind: Service
metadata:
  name: mysecondapp-service
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: mysecondapp
  ports:
    - port: 80          # Service port
      targetPort: 80   # Container port

---

apiVersion: v1
kind: Service
metadata:
  name: mythirdapp-service
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: mythirdapp
  ports:
    - port: 80          # Service port
      targetPort: 80   # Container port

